[package]
name = "fastgeotoolkit"
version = "0.1.3"
edition = "2021"
description = "A novel high-performance geospatial analysis framework with advanced route density mapping algorithms"
license = "MIT"
repository = "https://github.com/strava-tools/fastgeotoolkit"
homepage = "https://github.com/strava-tools/fastgeotoolkit"
documentation = "https://docs.rs/fastgeotoolkit"
authors = ["fastgeotoolkit contributors"]
keywords = ["gps", "geospatial", "trajectory", "route-density", "heatmap"]
categories = ["science", "algorithms", "data-structures", "visualization"]
readme = "README.md"
exclude = ["target/", "pkg/", "*.wasm"]

[lib]
crate-type = ["cdylib", "rlib"]
name = "fastgeotoolkit"

[dependencies]
gpx = "0.10"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

# Optional WebAssembly support
wasm-bindgen = { version = "0.2", features = ["serde-serialize"], optional = true }
js-sys = { version = "0.3", optional = true }
serde-wasm-bindgen = { version = "0.6", optional = true }

[dependencies.web-sys]
version = "0.3"
features = ["console"]
optional = true

[features]
default = []
wasm = ["wasm-bindgen", "js-sys", "serde-wasm-bindgen", "web-sys"]

[[example]]
name = "basic_usage"
path = "examples/basic_usage.rs"

[[example]]
name = "route_density"
path = "examples/route_density.rs"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
